# Generated by Django 4.2.2 on 2023-06-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_rename_img_category_image_rename_img_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
